name: E2E on Chrome

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cypress.io
        uses: cypress-io/github-action@v3
        with:
          project: ./site
          browser: chrome
          start:  npm run cypress:open 
          wait-on: "http://localhost:3000"
       
 