name: Cypress Cloud Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # O la versión que necesites
      - name: Install dependencies
        run: npm install
        working-directory: ./e2e
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.5.0
        with:
          start:  npm run cypress:open
          working-directory: ./e2e
          record: true
          parallel: true 
        env:
          AUTH_AUDIENCE: ${{ secrets.AUTH_AUDIENCE }}
          AUTH_URL: ${{ secrets.AUTH_URL }}
          AUTH_BASE_URL: ${{ secrets.AUTH_BASE_URL }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
          AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
          AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}