name: Cypress Cloud Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # O la versión que necesites
      - name: Install dependencies
        run: npm install
        working-directory: ./e2e
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.5.0
        with:
          start:  npm run cypress:open
          working-directory: ./e2e
          record: true
          parallel: true 
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}