name: E2E Docker test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Build Docker image
          run: docker build -t cypresse2e:v3 .
          working-directory: ./e2e
       
        - name: Cypress tests
          uses: ./
          with:
            working-directory: ./e2e

         