name: E2E Docker test
on: [push]
jobs:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Build Docker image
          run: docker build -t cypresse2e:v3 .
          working-directory: ./e2e
        
        - name: List all files in repository for debugging
          run: ls -R
        
        - name: Run Cypress tests
          working-directory: ./e2e
          run: |
            docker run -v $(pwd):/e2e -w /e2e -t -e "DEBUG=cypress:*" cypresse2e:v3 --spec cypress/e2e/*/*.feature
          env:
            CYPRESS_AUTH_AUDIENCE: ${{ secrets.AUTH_AUDIENCE }}
            CYPRESS_AUTH_URL: ${{ secrets.AUTH_URL }}
            CYPRESS_AUTH_BASE_URL: ${{ secrets.AUTH_BASE_URL }}
            CYPRESS_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
            CYPRESS_AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
            CYPRESS_AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
            CYPRESS_AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
            CYPRESS_AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}