name: E2E Docker test
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t cypresse2e:v3 .

    - name: Set NODE_PATH environment variable
      run: echo "NODE_PATH=$(npm root -g)" >> $GITHUB_ENV

    - name: Run Cypress tests
      run: docker run --env NODE_PATH=$NODE_PATH cypresse2e:v3