name: E2E Docker test
on: [push]
jobs:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Build Docker image
          run: docker build -t cypresse2e:v3 .
          working-directory: ./e2e

        - name: Validate installation
          run: docker run cypresse2e:v3 npm list --depth=0
        
        - name: List all files in repository for debugging
          run: ls -R
        
        - name: Run Cypress tests
          run: |
            docker run -v $(pwd):/e2e -w /e2e cypresse2e:v3 npx cypress verify
            docker run -v $(pwd):/e2e -w /e2e -t -e "DEBUG=cypress:*" cypresse2e:v3 --spec cypress/e2e/*/*.feature
          working-directory: ./e2e

         